[tool.poetry]
name = "coomm"
version = "0.1.1"
description = "Control Oriented Muscle Model for an octopus arm."
authors = ["hanson-hschang <hschang@illinois.edu>", "Seung Hyun Kim <skim449@illinois.edu>"]
license = "MIT"
readme = "README.md"

classifiers = [
# Trove classifiers
# Full list: https://pypi.python.org/pypi?%3Aaction=list_classifiers
"License :: OSI Approved :: MIT License",
"Development Status :: 4 - Beta",
"Programming Language :: Python",
"Programming Language :: Python :: 3.10",
"Programming Language :: Python :: 3.11",
"Programming Language :: Python :: 3.12",
"Programming Language :: Python :: 3.13",
"Programming Language :: Python :: 3.14",
"Programming Language :: Python :: 3.15",
"Intended Audience :: Science/Research",
"Intended Audience :: Education",
]
packages = [
    { include = "examples" },
    { include = "coomm" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.16"
numba = ">=0.61,<1"
numpy = ">=1.26,<3"
pyelastica = ">=0.2.2,<2"
matplotlib = ">=3.8,<4"


[tool.poetry.group.test.dependencies]
pytest = ">=8,<10"

[build-system]
requires = ["poetry-core>=2,<3"]
build-backend = "poetry.core.masonry.api"
